### ISSUE TITLE
Create <meta> tag if it's not there.

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [slackhq/csp-html-webpack-plugin#12]
### Description

The `<meta http-equiv="content-security-policy" content="">` tag should be created automatically if it's not present in the template.

Not everyone uses an explicit template, and instead uses the template automatically generated by HtmlWebpackPlugin.

### What type of issue is this?
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by AnujRNair** [comment]
Added via PR https://github.com/slackhq/csp-html-webpack-plugin/pull/13
