### ISSUE TITLE
Not generating meta tag

### ISSUE THREAD

**Issue by brymon68** [slackhq/csp-html-webpack-plugin#36]
### Description
I use an ejected CRA webpack.config.js. When adding your plugin and trying to generate a CSP meta tag, nothing is appended to HTML. Any idea how I can get this to work? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

cra 2.0.0

node version: 8.6

OS version(s):

#### Steps to reproduce:

Here is my webpack.config.js snippet: 
```
new HtmlWebpackPlugin(
        {
          cspPlugin: {
            enabled: true,
            policy: {
              'base-uri': "'self'",
              'object-src': "'none'",
              'script-src': ["'unsafe-inline'", "'self'", "'unsafe-eval'"],
              'style-src': ["'unsafe-inline'", "'self'", "'unsafe-eval'"]
            },
            hashEnabled: {
              'script-src': true,
              'style-src': true
            },
            nonceEnabled: {
              'script-src': true,
              'style-src': true
            }
          }
        },
        {
          inject: true,
          template: paths.appHtml,
        },
        isEnvProduction
          ? {
            minify: {
              removeComments: true,
              collapseWhitespace: true,
              removeRedundantAttributes: true,
              useShortDoctype: true,
              removeEmptyAttributes: true,
              removeStyleLinkTypeAttributes: true,
              keepClosingSlash: true,
              minifyJS: true,
              minifyCSS: true,
              minifyURLs: true,
            },
          }
          : undefined
      ),

      new CspHtmlWebpackPlugin({
        'base-uri': "'self'",
        'object-src': "'none'",
        'script-src': ["'unsafe-inline'", "'self'", "'unsafe-eval'"],
        'style-src': ["'unsafe-inline'", "'self'", "'unsafe-eval'"]
      }, {
          enabled: true,
          hashingMethod: 'sha256',
          hashEnabled: {
            'script-src': true,
            'style-src': true
          },
          nonceEnabled: {
            'script-src': true,
            'style-src': true
          }
        }),
```
#### Expected result:

<meta> tag appended to html

#### Actual result:

Nothing is appended

**Comment by brymon68** [comment]
Edit: this can be closed

**Comment by AndrewCraswell** [comment]
@brymon68 I'm experiencing this issue as well. What was your solution?
